### ISSUE TITLE
run error "Parameter regionStart was greater than regionEnd"

### ISSUE THREAD

**Issue by Gongjiao94** [DecodeGenetics/LRcaller#12]
Hi
  It occurs the error messgae of "Parameter regionStart was greater than regionEnd" when I run LRcaller. I checked the SVs in the input vcf file, and did not found SVs whose start position is greater than end position. So could you please give me some suggestions to debug the error? or display the specific SV that cause the error message? In addition, the SV calls in the input vcf file are generated by cuteSV, and are merged by Jasmine. The versison of LRcaller I used is v1.0.

Thanks in advance
Jiao

**Comment by h-2** [comment]
Hi and sorry for the late reply!

The problem is not being produced by LRcaller, but by the SeqAn library that we are using. I could try to debug this, if you can make a minimal input file available that reproduces the problem.

**Comment by Gongjiao94** [comment]
Hi, thanks for your reply, I have solved it by removing SVs on non-autosomal chromosomes.

**Comment by vkaz39** [comment]
Hello, 

I am having the same issue. Is there anyone who solved it without removing data? Thanks.
